# https://travis-ci.org/pytorch/pytorch
language: python
dist: trusty
git:
  submodules: false

# This reportedly works around an issue downloading packages from pypi on
# travis.  Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

env:
  global:
    - ECR_DOMAIN=308535385114.dkr.ecr.us-east-1.amazonaws.com
    - IMAGE_TAG=226
    - SCCACHE_BUCKET=ossci-compiler-cache

matrix:
    fast_finish: true
    include:
      - env: LINT_CHECK
        python: "2.7"
        install: pip install flake8
        script: flake8
      - env: MYPY_TYPE_CHECK
        python: "3.6"
        install: pip install mypy mypy-extensions
        script: mypy @mypy-files.txt
      - env: BUILD_ENVIRONMENT=pytorch-linux-trusty-py3.6-gcc7
        sudo: required
        services:
          - docker
      - env: BUILD_ENVIRONMENT=pytorch-linux-xenial-cuda9.2-cudnn7-py3-gcc7
        sudo: required
        services:
          - docker

install:
  - sudo pip install awscli
  - eval $(aws ecr get-login --region us-east-1 --no-include-email) # needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - echo "$ECR_DOMAIN/pytorch/$BUILD_ENVIRONMENT:$IMAGE_TAG"
  - docker pull "$ECR_DOMAIN/pytorch/$BUILD_ENVIRONMENT:$IMAGE_TAG"
script:
  - id=$(docker run -t -d -w /var/lib/jenkins "$ECR_DOMAIN/pytorch/$BUILD_ENVIRONMENT:$IMAGE_TAG")
  - docker cp "$TRAVIS_BUILD_DIR/." "$id:/var/lib/jenkins/workspace"
  - (echo "export SCCACHE_BUCKET=$SCCACHE_BUCKET" && echo 'sudo chown -R jenkins workspace && cd workspace && git submodule update --init && .jenkins/pytorch/build.sh && .jenkins/pytorch/test.sh') | docker exec -u jenkins -i "$id" bash
